### ISSUE TITLE
Unnecessary commits for notes

### ISSUE THREAD

**Issue by SysSn13** [QasimWani/LeetHub#135]
LeetHub is uploading notes for all the problems even if it is empty. It is not a good idea to commit an empty file for every submission.
**To Reproduce**
- regular submission for any problem

**Expected behavior**
Commit the notes only when something is written by the user or there are some new changes in the notes.

**Comment by QasimWani** [comment]
what do you mean `notes`? is it ReadMe? If so, i'm unable to reproduce it. it has been working fine so far. Please list exact procedure (and screenshots) to reproduce. Was this a one-off thing? Perhaps wait a little longer before switching/closing tabs? Have you tried reloading and resubmitting again?

**Comment by SysSn13** [comment]
See [this](https://github.com/QasimWani/LeetHub/blob/b5a6afa89d44a4c8559fbae950d64f9d614dcf8e/scripts/leetcode.js#L554). Well It's not updated on the chrome web-store yet.

**Comment by byamir** [comment]
Also having this issue
![Screen Shot 2022-01-10 at 3 24 55 PM](https://user-images.githubusercontent.com/25187424/148834143-b9c85037-c2e6-4d9d-ac93-0fecf03df238.jpg)

**Comment by QasimWani** [comment]
Yeah I'm itching it up by temporarily removing the notes feature. That should solve this problem for now. Apologies for the buggy release.

**Comment by sarthak1905** [comment]
Hey, has the feature been removed yet? After I made the submission today, empty ```Notes.md``` files were committed and I had to delete them on my own.

**Comment by SP-XD** [comment]
> Hey, has the feature been removed yet? After I made the submission today, empty `Notes.md` files were committed and I had to delete them on my own.

[same here bro ](https://i.imgur.com/zpO99IG.png)

**Comment by NikitaShkaruba** [comment]
There's a duplicate thread https://github.com/QasimWani/LeetHub/issues/195
Still not implemented. Waiting for the release! :)

**Comment by VinayLodhi1712** [comment]
Please implement this feature on chrome extensions store. The notes.md file is always committing unnecessarily. Plz remove this.

**Comment by irohanrajput** [comment]
is there a way to avoid committing NOTES.md & README.md ??
